SELECT TOP (1000) [Id]
      ,[Site_Id]
      ,[SiteName]
      ,[SiteUrl]
      ,[Session_Id]
      ,[Executor]
      ,[SessionStart]
      ,[SessionEnd]
      ,[Overline]
      ,[Headline]
      ,[Subline]
      ,[Author]
      ,[PublicDate]
      ,[Url]
      ,[Items]
      ,[ItemsCount]
  FROM [WebScraper].[dbo].[VwArticles]
